---
title: "Sagebrush Genome Project"
output:
  bookdown::html_document2: 
    toc: TRUE
    toc_float: TRUE
link-citations: yes
fontsize: 12pt
bibliography: References.bib
---

# Aim

Sequencing, phasing and annotating the diploid genome of basin big sagebrush (*Artemisia tridentata* subsp. *tridentata*). This taxon as 2n=2x=18 chromosomes and a 2C genome size of 9.5Gbp [see @Barron2020]. In addition, preliminary analyses demonstrated that the genome is highly out-bred. For these reasons, we are aiming at not only produce enough biomass of the same individual line to produce the genome, but also maintain the individual line both *in vitro* and *ex vitro* to support genotype-by-environment experiments. 

# Overall approach & Requirements

To be able to phase such complex genome, we aim at generating 50-100X raw data coverage (haploid sagebrush genome size: 4.5 Gbp) using PacBio technology and phase it using proximity ligation data. Such wet-lab procedures are requiring the production of ca. **120 gr. of leaf biomass**.

Please see the following section of the website for more details on:

- [Biomass production](Biomass_production.html).
- [Sequencing & Bioinformatics](Sequencing.html).

# Meet the team

## At Boise State University

- **Sven Buerki, Ph.D** (sven.buerki@boisestate.edu): Assistant Professor at Boise State University and PI of this project funded by [GEM3](funding.html).
- **Peggy Martinez, M.S.** (peggymartinez@boisestate.edu): Laboratory Technician leading the sagebrush *in vitro*  culture program at Boise State University. 
- **Rachael Barron, M.S.** (rachael.barron@simplot.com): Associate Scientist at Simplot who has contributed her expertise on *in vitro* culture to this project.
- **Marcelo Serpe, Ph.D**: Professor at Boise State University.
- **Anthony Melton, Ph.D.**:
- **Stephen Novak, Ph.D.**:
- **Jennifer Forbey, Ph.D.**:

## At Dovetail Genomics

- Current contact **Mark Daly** (mark@dovetail-genomics.com). The company will assign a project manager as soon as we have a signed contract.

## At HudsonAlpha

- **Jeremy Schmutz**
- **Jane Grimwood, Ph.D.**

# References